name: workflow1

on:
    push:
        branches: 
            - main

    pull_request:
        branches: 
            - main

jobs:
    build_job:
          runs-on: ubuntu-latest

          steps:
            - name: display message
              run: echo "mfjdf"

            - name: copy the repo to remote
              uses: actions/checkout@v4

            - name: name of the trigger
              run: echo "the trigger for this job is ${{github.event_name}}"
